{{- range $task := .Values.tasks }}
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ lower $task.taskName }}-worker
spec:
  template:
{{/*    metadata:                                                                         */}}
{{/*      annotations:                                                                    */}}
{{/*        autoscaling.knative.dev/initial-scale: {{ $task.initialScale | default "0"}}  */}}
{{/*        autoscaling.knative.dev/max-scale: {{ $task.maxScale | default "0"}}          */}}
    spec:
      containerConcurrency: 1
      containers:
        - image: {{ $task.workerImage }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
          - name: REDIS_URL
            value: {{ $task.redisUrl | default "redis://redis.default:6379"}}
          workingDir: {{ $task.workingDir | default "/work_dir"}}
          volumeMounts:
          - name: nfs
            mountPath: {{ $task.workingDir | default "/work_dir"}}
          resources:
            requests:
              cpu: {{ $task.cpuRequest | default "500m"}}
              memory: {{ $task.memoryRequest | default "512Mi"}}
            limits:
              cpu: {{ $task.cpuLimit | default "2"}}
              memory: {{ $task.memoryLimit | default "2Gi"}}
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
---
{{- end }}
